# Generated by Django 4.2.7 on 2024-01-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='bank_rupt',
            field=models.BooleanField(default=False),
        ),
    ]
