# Generated by Django 4.2.7 on 2023-12-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_transactions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='load_approve',
            new_name='loan_approve',
        ),
    ]
